http://localhost:3000/api/repos/
###
http://localhost:3000/api/repos/front-end/commits/master
###
http://localhost:3000/api/repos/front-end/commits/d925652
###
http://localhost:3000/api/repos/front-end/commits/d925652/page/start/0/limit/1
###
http://localhost:3000/api/repos/front-end/commits/d925652/page/start/1/limit/1
###
http://localhost:3000/api/repos/front-end/commits/d925652/diff
###
http://localhost:3000/api/repos/front-end
###
http://localhost:3000/api/repos/front-end/tree/develop
###
http://localhost:3000/api/repos/front-end/tree/b7a5761
###
http://localhost:3000/api/repos/front-end/tree/b7a5761/Front
###
http://localhost:3000/api/repos/front-end/tree/9c3dc02/Tests/AA-api-tests
###
http://localhost:3000/api/repos/front-end/blob/9c3dc02/Tests/AA-api-tests/AA-api-tests.prj
###
http://localhost:3000/api/repos/front-end/blob/9c3dc02/README.md
###
DELETE http://localhost:3000/api/repos/Finance HTTP/1.1
###
POST http://localhost:3000/api/repos HTTP/1.1
Content-Type: application/json

{
  "url": "https://github.com/Muxa89/Finance.git"
}
###